# Generated by Django 4.2.3 on 2023-07-20 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showcase_app", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_body",
            new_name="body",
        ),
    ]
