# Generated by Django 4.2.3 on 2023-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase_app", "0003_rename_comment_body_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
