# Generated by Django 4.2.3 on 2023-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase_app", "0005_product_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/%Y/%m/%d"),
        ),
    ]
