# Generated by Django 4.2.3 on 2023-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase_app", "0009_remove_product_image_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="images/%Y/%m/%d"),
        ),
    ]
