# Generated by Django 4.2.3 on 2023-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase_app", "0010_alter_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
