# Generated by Django 4.2.3 on 2023-07-29 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showcase_app", "0011_comment_archived"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="Question",
            new_name="question_id",
        ),
    ]
