# Generated by Django 4.2.3 on 2023-08-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
        ("showcase_app", "0013_rename_question_id_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.baseuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.baseuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.baseuser",
            ),
            preserve_default=False,
        ),
    ]
