# Generated by Django 4.2.3 on 2023-08-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
        ("showcase_app", "0014_answer_user_comment_user_question_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.baseuser",
            ),
            preserve_default=False,
        ),
    ]
