# Generated by Django 4.2.3 on 2023-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="moder",
            field=models.BooleanField(default=False),
        ),
    ]
